## Tutorial of Interventions on Non-transformer Model: MLPs

In [1]:
__author__ = "Zhengxuan Wu"
__version__ = "12/20/2023"

### Overview

This tutorials show how to use this library on non-transformer models, such as MLPs. The set-ups are pretty much the same as standard transformer-based models.

### Set-up

In [2]:
try:
    # This library is our indicator that the required installs
    # need to be done.
    import transformers
    import sys
    sys.path.append("align-transformers/")
except ModuleNotFoundError:
    !git clone https://github.com/frankaging/align-transformers.git
    !pip install -r align-transformers/requirements.txt
    import sys
    sys.path.append("align-transformers/")

In [3]:
import sys
sys.path.append("../..")

import torch
import pandas as pd
from models.basic_utils import embed_to_distrib, top_vals, format_token
from models.configuration_alignable_model import AlignableRepresentationConfig, AlignableConfig
from models.alignable_base import AlignableModel
from models.interventions import VanillaIntervention, RotatedSpaceIntervention
from models.mlp.modelings_mlp import MLPConfig
from models.mlp.modelings_alignable_mlp import create_mlp_classifier

%config InlineBackend.figure_formats = ['svg']
from plotnine import ggplot, geom_tile, aes, facet_wrap, theme, element_text, \
                     geom_bar, geom_hline, scale_y_log10

config, tokenizer, mlp =create_mlp_classifier(MLPConfig(h_dim=32))

loaded model


### Intervene in middle layer by partitioning representations into subspaces

MLP layer may contain only a single "token" representation each layer. As a result, we often want to intervene on a subspace of this "token" representation to localize a concept.

In [4]:
alignable_config = AlignableConfig(
    alignable_model_type=type(mlp),
    alignable_representations=[
        AlignableRepresentationConfig(
            0,
            "block_output",
            "pos",                              # mlp layer creates a single token reprs
            1,
            subspace_partition=[[0,16],[16,32]] # partition into two sets of subspaces
        ),
    ],
    alignable_interventions_type=RotatedSpaceIntervention,
)
alignable = AlignableModel(alignable_config, mlp)

base = {"inputs_embeds": torch.rand(1, 1, 32)}
source = {"inputs_embeds": torch.rand(1, 1, 32)}
print("base", alignable(base))
print("source", alignable(source))

base ((tensor([[[-0.0552, -0.1310]]]),), None)
source ((tensor([[[-0.0507, -0.1348]]]),), None)


In [5]:
_, counterfactual_outputs = alignable(
    base,
    [source],
    {"sources->base": ([[[0]]], [[[0]]])},
    subspaces = [[[0, 1]]]
)

In [6]:
counterfactual_outputs # this should be the same as source.

(tensor([[[-0.0507, -0.1348]]], grad_fn=<UnsafeViewBackward0>),)

### Intervene the subspace with multiple sources

In [19]:
alignable_config = AlignableConfig(
    alignable_model_type=type(mlp),
    alignable_representations=[
        AlignableRepresentationConfig(
            0,
            "block_output",
            "pos",                               # mlp layer creates a single token reprs
            1,
            subspace_partition=[[0,16],[16,32]], # partition into two sets of subspaces
            intervention_link_key=0
        ),
        AlignableRepresentationConfig(
            0,
            "block_output",
            "pos",                               # mlp layer creates a single token reprs
            1,
            subspace_partition=[[0,16],[16,32]], # partition into two sets of subspaces
            intervention_link_key=0
        ),
    ],
    alignable_interventions_type=RotatedSpaceIntervention,
)
alignable = AlignableModel(alignable_config, mlp)

base = {"inputs_embeds": torch.rand(10, 1, 32)}
source = {"inputs_embeds": torch.rand(10, 1, 32)}
print("base", alignable(base))
print("source", alignable(source))

base ((tensor([[[-0.0509, -0.1246]],

        [[-0.0500, -0.1376]],

        [[-0.0503, -0.1381]],

        [[-0.0531, -0.1431]],

        [[-0.0601, -0.1424]],

        [[-0.0522, -0.1357]],

        [[-0.0543, -0.1488]],

        [[-0.0585, -0.1420]],

        [[-0.0583, -0.1354]],

        [[-0.0481, -0.1367]]]),), None)
source ((tensor([[[-0.0561, -0.1357]],

        [[-0.0556, -0.1486]],

        [[-0.0540, -0.1409]],

        [[-0.0476, -0.1243]],

        [[-0.0512, -0.1490]],

        [[-0.0539, -0.1368]],

        [[-0.0496, -0.1438]],

        [[-0.0534, -0.1383]],

        [[-0.0564, -0.1366]],

        [[-0.0512, -0.1380]]]),), None)


In [20]:
_, counterfactual_outputs = alignable(
    base,
    [source, None],
    {"sources->base": ([[[0]]*10, None], [[[0]]*10, None])},
    subspaces = [[[0]]*10, None]
)

In [21]:
counterfactual_outputs

(tensor([[[-0.0544, -0.1337]],
 
         [[-0.0517, -0.1489]],
 
         [[-0.0518, -0.1376]],
 
         [[-0.0536, -0.1340]],
 
         [[-0.0486, -0.1421]],
 
         [[-0.0484, -0.1325]],
 
         [[-0.0539, -0.1480]],
 
         [[-0.0532, -0.1326]],
 
         [[-0.0575, -0.1362]],
 
         [[-0.0530, -0.1421]]], grad_fn=<UnsafeViewBackward0>),)

In [22]:
_, counterfactual_outputs = alignable(
    base,
    [None, source],
    {"sources->base": ([None, [[0]]*10], [None, [[0]]*10])},
    subspaces = [None, [[0]]*10]
)

In [23]:
counterfactual_outputs

(tensor([[[-0.0544, -0.1337]],
 
         [[-0.0517, -0.1489]],
 
         [[-0.0518, -0.1376]],
 
         [[-0.0536, -0.1340]],
 
         [[-0.0486, -0.1421]],
 
         [[-0.0484, -0.1325]],
 
         [[-0.0539, -0.1480]],
 
         [[-0.0532, -0.1326]],
 
         [[-0.0575, -0.1362]],
 
         [[-0.0530, -0.1421]]], grad_fn=<UnsafeViewBackward0>),)

In [24]:
_, counterfactual_outputs = alignable(
    base,
    [source, source],
    {"sources->base": ([[[0]]*10, [[0]]*10], [[[0]]*10, [[0]]*10])},
    subspaces = [[[0]]*10, [[1]]*10]
)

In [25]:
counterfactual_outputs

(tensor([[[-0.0561, -0.1357]],
 
         [[-0.0556, -0.1486]],
 
         [[-0.0540, -0.1409]],
 
         [[-0.0476, -0.1243]],
 
         [[-0.0512, -0.1490]],
 
         [[-0.0539, -0.1368]],
 
         [[-0.0496, -0.1438]],
 
         [[-0.0534, -0.1383]],
 
         [[-0.0564, -0.1366]],
 
         [[-0.0512, -0.1380]]], grad_fn=<UnsafeViewBackward0>),)